### ISSUE TITLE
June 2020: License has expired

### ISSUE THREAD

**Issue by james-em** [puarudz/Directadmin-1.61.0-Nulled#1]
The license has expired :(

**Comment by popularitate** [comment]
Same here,

License has expired
Current Server Time: Sun Jul 5 18:14:00 2020

How you overcome this ?

**Comment by jamesst20** [comment]
> Same here,
> 
> License has expired
> Current Server Time: Sun Jul 5 18:14:00 2020
> 
> How you overcome this ?

Don't bother using Direct Admin, I have switched to CyberPanel which is free, open source and get's exactly the same job done. That's how I overcame this :)
